# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    library_directory: '%kernel.root_dir%/Resources/library'

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
