parameters:
    sphinx_host: 127.0.0.1
    sphinx_port: 9312
    sphinx_collection: library

services:
    app.twig.menu_extension:
        class: AppBundle\Twig\Extension\Menu
        arguments:  ['@doctrine']
        tags:
            - { name: twig.extension }

    app.twig.pagination_extension:
        class: AppBundle\Twig\Extension\Pagination
        arguments:  ['@service_container']
        tags:
            - { name: 'twig.extension' }

    search_manager:
        class:            AppBundle\Service\SearchManager
        arguments:
            -             '@router'
            -             '%sphinx_host%'
            -             '%sphinx_port%'
            -             '%sphinx_collection%'
